config/routes.rb
Riki::Application.routes.draw do
  
  resources :groups

  resources :pages
  
  get "page/:id/history" => "pages#history", :as => "history"
  get "page/:id/revert" => "pages#revert", :as => "revert_page"
  
  root :to => "pages#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name
  has_many :pages
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :title, :body, :group_id
  has_paper_trail

  has_many :tags
  belongs_to :group

  def self.pages_by_tag(string)
    pages = []
    Tag.where(tag_name: string).each do |tag|
      pages << Page.find(tag.page_id)
    end
    return pages
  end

  def add_tags(tags)
  	tags.split(" ").each do |t|
  		self.tags.create(tag_name: t)
  	end
  end
  
  def delete_tags
  	self.tags.each do |t|
  		t.destroy
  	end
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :page
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(params[:group])
    if @group.save
      redirect_to root_path, notice: 'Group Created'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      redirect_to root_path, notice: 'Group Saved'
    else
      render :edit
    end
  end

end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
  def revert
    @history = Version.find(params[:id])

    if @history.reify
      @history.reify.save!
      redirect_to :back, :notice => "Undid #{@history.event}. #{link(@history)}"
    else
      @history.item.destroy
      redirect_to new_page_path, :notice => "Undid #{@history.event}. #{link(@history)}"
    end
  end

  def link_name  
    params[:redo] == "true" ? "undo" : "redo"
  end
  
  def link(history)
    view_context.link_to(link_name, revert_history_path(history.next, :redo => !params[:redo]), :method => :post)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @q = Page.search(params[:q])
    @pages = @q.result(distinct: true)
    @grouped = @pages.group_by { |p| p.group_id }.values
  end

  def show
    @page = Page.find(params[:id])
    @group = Group.find(@page.group_id) rescue nil
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(params[:page])
    if @page.save
      redirect_to page_path(@page), :notice => "page saved"
    else
      redirect_to new_page_path, :notice => "page not saved" 
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(params[:page])
      redirect_to page_path(@page), :notice => "page saved #{undo_link(@page)}"
    else
      redirect_to new_page_path, :notice => "page not saved" 
    end
  end

  def destroy
    @page = Page.find(params[:id])
    if @page.destroy
      redirect_to root_path, :notice => "page deleted"
    else
      redirect_to root_path, :notice => "page not deleted"
    end
  end

  def history
    @page = Page.find(params[:id])
    @versions = @page.versions
  end

  def revert
    @page = Page.find(params[:id])

    @page = @page.previous_version

    if @page.save
      redirect_to page_path(@page), :notice => "Undid changes"
    else
      redirect_to page_path(@page), :notice => "Failed to undo changes"
    end
  end

  private

  def undo_link(page)
    view_context.link_to("undo", revert_page_path(page))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, :lexer => language)
    end
  end

  def markdown(text)
    markdown = Redcarpet::Markdown.new(
      Redcarpet::Render::HTML.new(:safe_links_only => true),
      :fenced_code_blocks => true, :autolink => true
    )
    markdown.render(text || '').html_safe
  end

end

app/views/groups/_form.slim
.row
  .twelve.columns

    = form_for @group, html: { class: "form form-stacked" } do |f|
      .field
        = f.text_field :name, class: "input textarea page-body"

      .medium.danger.btn
        = f.submit class: ""

app/views/groups/edit.slim
= render "form"

app/views/groups/new.slim
= render "form"

app/views/layouts/application.slim
doctype html
html
  head
    title Riki
    meta charset="utf-8"
    meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"
    meta content="" name="description"
    meta content="" name="author"
    meta content="width=device-width" name="viewport"
    = csrf_meta_tags

    = stylesheet_link_tag "application", media: 'all'
    = javascript_include_tag "application"

  body
    .navbar
      .row
        ul.twelve.columns
          li: a href='/' Pages
          li: a href=new_page_path New Page
          li: a href=new_group_path New Group

    .row
      - flash.each do |name, msg|
        = content_tag :div, raw(msg), class: "flash alert #{name}"

    = yield

app/views/pages/_form.slim
.row.wide
  .six.columns
    h3 Edit

    = form_for @page, html: { class: "form form-stacked" } do |f|

      label Group
      .field
        = f.select :group_id, Group.all.collect { |g| [g.name, g.id] }, { include_blank: true }

      .field
        = f.text_field :title, placeholder: 'Title', class: 'input'
      
      .field
        = f.text_area :body, class: "input textarea page-body", rows: 15

      .medium.danger.btn
        = f.submit class: ""

  .six.columns
    h3 Preview
    .preview

app/views/pages/edit.slim
= render "form"

app/views/pages/history.slim
.row
  .twelve.columns
    table
      thead
        tr
          th Event
          th User
      tbody
        - @versions.each do |v|
          tr
            td = v.event
            td

app/views/pages/index.slim
.row
  .twelve.columns
    .page-header 
      .row
        .three.columns
          h3 All Pages
        .four.columns.push_five
          = search_form_for @q do |f|
            .field
              = f.text_field :title_or_body_cont, class: 'input', placeholder: 'Search'
    
    - @grouped.each do |g|
      h3 = Group.find(g.first.group_id).try(:name) rescue ''
      ul
        - g.each do |p|
          li
            .large.default.btn.block
              = link_to p.title, page_path(p)

app/views/pages/new.slim
= render "form"

app/views/pages/show.slim
.sub.navbar
  .row
    ul.twelve.columns
      li: .medium.metro.round.btn = link_to "Edit Page", edit_page_path(@page), class: ''
      li: .medium.metro.round.btn = link_to "Delete Page", page_path(@page), method: :delete, data: { confirm: 'Are you sure?' }, class: ''
      li: .medium.metro.round.btn = link_to "Page History", history_path(@page), class: ''

.row.wide
  .twelve.columns
    .page-header
      .row.wide
        .three.columns
          h3 = @page.title
        .five.columns.push_four
          h4 = @group.try(:name)

    .page
      = markdown(@page.body)